spring:
  datasource:
    url: jdbc:mysql://localhost/lab3?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 5890
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8081

